### ISSUE TITLE
Linux confirmation

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [RickStrahl/AlbumViewerVNext#10]
Hello, can confirm it works on linux without modification:
![screenshot_2017-10-10_15-21-22](https://user-images.githubusercontent.com/1392388/31413597-ed5bd026-adce-11e7-9e7a-8abffb3650c9.png)

I downloaded the files as a zip archive, unzipped it to a folder, opened the folder in Visual Studio Code editor, it prompted to restore requirements and then I selected Debug->Start debugging and the screenshot is from the result which seems to be working correctly.

**Comment by RickStrahl** [comment]
Awesome - thanks for checking it out. I've run under Docker so that verified but not under any desktop linux.

**Comment by WhatFreshHellIsThis** [comment]
Cool, thanks for the example project!
