### ISSUE TITLE
Problem running angular project

### ISSUE THREAD

**Issue by punkouter** [RickStrahl/AlbumViewerVNext#4]
I do npm install/npm start

The project loads but I get

 Unknown server failure. 

Am I suppose to first start 'AlbumViewerNetCore' as well in Visual studio so the services are there for the angular project to find ?

**Comment by RickStrahl** [comment]
Where you're getting these instructions from?  You shouldn't be running the sample server with npm start. You need to run `ng serve` to run the dev server. 

Please look at the install instructions on the main readme page.

Here are the client configuration steps:
https://github.com/RickStrahl/AlbumViewerVNext#to-develop-the-albumviewer-angular-2-example

**Comment by punkouter** [comment]
Still can't get it to work . Am I suppose to run the dotnet app and THEN the client app?  The client app is getting a server error.

**Comment by RickStrahl** [comment]
If you clone as is, the app should be able to run just from the .NET install as the built html and assets are all copied into the wwwroot folder.

The instructions on the [Readme page with Getting Started](https://github.com/RickStrahl/AlbumViewerVNext#getting-started) work for me as is from a freshly cloned repo.
