### ISSUE TITLE
How do you debug typescript when the project is not a csproj ? 

### ISSUE THREAD

**Issue by punkouter** [RickStrahl/AlbumViewerVNext#5]
The dotnet new angular example is easy because I can just set a breakpoint and run. 

But in VS2017 I cannot F5 run it and I guess it uses webpack so I can't debug in the browser.. Is there some simple way to set a break point on the typescript ?  (I can use VS code if that is the easiest way)

**Comment by RickStrahl** [comment]
The browser should let you step through typescript. Just use Chrome or FireFox debugging tools. Not sure about IE or Edge, but both Chrome and FF work with script maps to present the proper typescript code to step through.

Just add a `debugger` statement or set breakpoints in the respective debuggers.

VS 2017 should also allow you to attach directly to the Chrome Debugger.
