### ISSUE TITLE
404 error for .woff2 static files

### ISSUE THREAD

**Issue by mchubby** [RickStrahl/AlbumViewerVNext#8]
### Symptoms
Opening a woff2 URL such as `http://localhost:26448/fontawesome-webfont.af7ae505a9eed503f8b8.woff2` results in 404 error.

### Diagnosis

The web.config "wwwroot-static" rule https://github.com/RickStrahl/AlbumViewerVNext/blob/2807706094163f69380f4caab91172d220046d95/src/AlbumViewerNetCore/web.config#L11 is not greedy enough.

According to the development custom error, the rewritten URL points to `wwwroot\fontawesome-webfont.af7ae505a9eed503f8b8.woff` (notice missing trailing digit)

### Proposed Fix

Invert order in match expression:
```xml
<match url="([\S]+[.](html|htm|svg|js|css|png|gif|jpg|jpeg|woff2|woff))" />
```

**Comment by RickStrahl** [comment]
Previously fixed on the .NET Core 2.0 branch.

**Comment by mchubby** [comment]
Hi Rick,

It seems the fix never made its way to master: https://github.com/RickStrahl/AlbumViewerVNext/commits/master/src/AlbumViewerNetCore/web.config

Would you mind merging it again?
